openapi: 3.0.0
info:
  title: Mediator framework
  description: "This is a sample Mediator server.  You can find out more about our\
    \ project at [https://github.com/icanlab/mediator)"
  contact:
    email: icanlab@pub.seu.edu.cn
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://127.0.0.1/v1
  description: localhost
tags:
- name: Adaptor
  description: pasre msg function module
paths:
  /adaptor/translateMsg:
    post:
      tags:
      - Adaptor
      summary: translate msg
      operationId: translate_msg
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input_msg'
        required: false
      responses:
        "100":
          description: need more info
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                x-content-type: application/json
        "400":
          description: operation failed
      x-openapi-router-controller: swagger_server.controllers.adaptor_controller
components:
  schemas:
    input_msg:
      properties:
        protocol:
          type: string
        neid:
          type: string
        message:
          type: string
  securitySchemes: {}
  links: {}
  callbacks: {}

